server:
  port: 80

spring:

  application:
    name: spring-shop

####################################
# MySql Setting
####################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_a?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username : root
    password : 1234

####################################
# JPA Setting
####################################
  jpa:
    open-in-view: true
    hibernate:
      ddl_auto: create #create, update, none, create_drop, validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format.sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

####################################
# Log Setting
####################################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace